MachineSimulation.App/Areas/Admin/Controllers/OperationController.cs
using MachineSimulation.Business.Abstract;
using MachineSimulation.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Reflection.PortableExecutable;

namespace MachineSimulation.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class OperationController : Controller
    {
        private readonly IOperationService _operationService;
        private readonly IMachineService _machineService;
        public OperationController(IOperationService operationService, IMachineService machineService)
        {
            _operationService = operationService;
            _machineService = machineService;
        }

        public async Task<IActionResult> Index(int? machineId)
        {
            var machines = await _machineService.GetAllMachinesAsync();
            ViewBag.Machines = new SelectList(machines, "Id", "MachineName");

            if (machineId.HasValue && machineId > 0)
            {
                var filteredOperations = await _operationService.GetOperationsByMachineIdAsync(machineId.Value);
                return View(filteredOperations);
            }
            else
            {
                var model = await _operationService.GetAllOperationsAsync();
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update([FromRoute(Name = "id")] int id)
        {
            var model = await _operationService.GetByIdOperationAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] Operation operation)
        {
           
                try
                {
                    await _operationService.UpdateOperation(operation);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Güncelleme sırasında bir hata oluştu: " + ex.Message);
                }
            
            return View(operation);
        }



    }
}

MachineSimulation.App/Areas/Admin/Views/Operation/Index.cshtml
@model IEnumerable<Operation>
<link rel="stylesheet" href="~/css/admin-home.css" asp-append-version="true" />
<style>
    .form-group {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .form-group h5 {
        margin: 0;
    }

    .form-group select {
        width: auto;
        margin-left: 10px;
    }

    .form-group button {
        margin-left: 10px;
    }
</style>

<div class="display-6 text-center">
    <h1>Operasyonlar</h1>

    <div class="table-container">
        <div class="form-group">
            <h5>
                <i class="fa-solid fa-filter"></i>
            </h5>
            <select class="form-control" id="operationMachineFilter" name="machineFilter" style="width: auto; margin-left: 10px;">
                <option value="">Makine Seçiniz</option>
                @foreach (var machine in ViewBag.Machines)
                {
                    <option value="@machine.Value">@machine.Text</option>
                }
            </select>
            <button type="button" class="btn btn-secondary" id="operationNoFilterButton" style="margin-left: 10px;">
                <i class="fa-solid fa-filter-circle-xmark"></i>
                Filtreyi Kaldır
            </button>
        </div>

        <table class="table table-striped table-hover">
            <thead class="thead-all">
                <tr>
                    <th>Makine</th>
                    <th>Operasyon Adı</th>
                    <th>Modbus Adres</th>
                    <th>Modbus Adres Türü</th>
                    <th>Değişiklikler</th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var oprt in Model)
                {
                    <tr>
                        <td>@(oprt.Machine != null ? oprt.Machine.MachineName : "Makine Yok")</td>
                        <td>@oprt.OperationName.Name</td>
                        <td>@oprt.ModbusIp</td>
                        <td>@oprt.ModbusIpType</td>
                        <td>
                            <a class="btn btn-warning" asp-action="Update" asp-controller="Operation" asp-route-id="@oprt.Id">
                                <i class="fa fa-edit"></i>
                                <span>Güncelle</span>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var machineFilter = document.getElementById('operationMachineFilter');
            var selectedMachineId = localStorage.getItem('selectedOperationMachineId');
            if (selectedMachineId) {
                machineFilter.value = selectedMachineId;
            }

            machineFilter.addEventListener('change', function () {
                var selectedMachineId = this.value;
                localStorage.setItem('selectedOperationMachineId', selectedMachineId);
                var url = '@Url.Action("Index", "Operation", new { area = "Admin" })' + '?machineId=' + selectedMachineId;
                window.location.href = url;
            });

            document.getElementById('operationNoFilterButton').addEventListener('click', function () {
                localStorage.removeItem('selectedOperationMachineId');
                window.location.href = '@Url.Action("Index", "Operation", new { area = "Admin" })';
            });
        });
    </script>
}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

MachineSimulation.App/Areas/Admin/Views/Operation/Update.cshtml
@model Operation

<div class="text-center">
    <div class="display-6">
        Güncelle
    </div>
</div>

<div class="form-style">
    <form asp-action="Update" method="post" enctype="multipart/form-data">
        <div class="text-danger" asp-validation-summary="All"></div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="OperationNameId" />
        <input type="hidden" asp-for="MachineId" />


        <div class="form-group">
            <label asp-for="OperationName.Name" class="form-label">Operasyon Adı</label>
            <input type="text" class="form-control rounded" value="@Model.OperationName.Name" readonly style="width: 100%;">
        </div>

        <div class="form-group">
            <label asp-for="Machine.MachineName" class="form-label">Makine</label>
            <input type="text" class="form-control rounded" value="@Model.Machine.MachineName" readonly style="width: 100%;">
        </div>


        <div class="form-group">
            <label asp-for="ModbusIp" class="form-label">Modbus Adres</label>
            <input type="text" asp-for="ModbusIp" class="form-control rounded" required style="width: 100%;">
        </div>
        <div class="form-group">
            <label asp-for="ModbusIpType">Modbus Adres Türü</label>
            <select asp-for="ModbusIpType" class="form-control">
                <option value="bool">Bool</option>
                <option value="int">Int</option>
            </select>
        </div>

        <div class="form-group my-3">
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-save"></i>
                Güncelle
            </button>
            <a asp-action="Index" class="btn btn-warning">
                <i class="fa fa-list"></i>
                Operasyonlar
            </a>
        </div>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>