MachineSimulation.App/Areas/Admin/Controllers/RoleController.cs
using MachineSimulation.Business.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MachineSimulation.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly IAuthService _authService;

        public RoleController(IAuthService authService)
        {
            _authService = authService;
        }

        public IActionResult Index()
        {
            return View(_authService.Roles);
        }
    }
}

MachineSimulation.App/Areas/Admin/Controllers/StoppageController.cs
using MachineSimulation.Business.Abstract;
using MachineSimulation.Business.Concrete;
using MachineSimulation.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MachineSimulation.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class StoppageController : Controller
    {
        private readonly IStoppageService _stoppageService;
        private readonly IMachineService _machineService;

        public StoppageController(IStoppageService stoppageService, IMachineService machineService)
        {
            _stoppageService = stoppageService;
            _machineService = machineService;
        }

        public async Task<IActionResult> Index(int? machineId)
        {
            var machines = await _machineService.GetAllMachinesAsync();
            ViewBag.Machines = new SelectList(machines, "Id", "MachineName");

            if (machineId.HasValue && machineId > 0)
            {
                var filteredStoppages = await _stoppageService.GetStoppagesByMachineIdAsync(machineId.Value);
                return View(filteredStoppages);
            }
            else
            {
                var model = await _stoppageService.GetAllStoppageAsync();
                return View(model);
            }
        }

        public async Task<IActionResult> Create()
        {
            var machines = await _machineService.GetAllMachinesAsync();
            ViewBag.Machines = new SelectList(machines, "Id", "MachineName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] Stoppage stoppage)
        {

            await _stoppageService.AddStoppageAsync(stoppage);
            var machines = await _machineService.GetAllMachinesAsync();
            ViewBag.Machines = new SelectList(machines, "Id", "MachineName");
            return RedirectToAction("Index");
        }



        public async Task<IActionResult> Update([FromRoute(Name = "id")] int id)
        {
            var model = await _stoppageService.GetByIdStoppageAsync(id);
            var machine = await _machineService.GetByIdMachineAsync(model.MachineId);

            if (model.Machine == null)
            {
                model.Machine = new Machine();
            }

            model.Machine.MachineName = machine.MachineName; // Makinenin adını modele ekliyoruz
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] Stoppage stoppage)
        {
            var existingStoppage = await _stoppageService.GetByIdStoppageAsync(stoppage.Id);
            existingStoppage.ReasonStoppageName = stoppage.ReasonStoppageName;
            existingStoppage.ReasonStoppageValue = stoppage.ReasonStoppageValue;

            await _stoppageService.UpdateStoppage(existingStoppage);
            return RedirectToAction("Index");
        }




        public async Task<IActionResult> Delete([FromRoute(Name = "id")] int id)
        {
            var existingStoppage = await _stoppageService.GetByIdStoppageAsync(id);
            if (existingStoppage == null)
            {
                return NotFound();
            }

            var deleteOperation = await _stoppageService.DeleteOneStoppage(id);

            return RedirectToAction("Index");
        }



    }
}

MachineSimulation.App/Areas/Admin/Controllers/UserController.cs
using MachineSimulation.Business.Abstract;
using MachineSimulation.Entities.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MachineSimulation.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IAuthService _authService;

        public UserController(IAuthService authService)
        {
            _authService = authService;
        }

        public IActionResult Index()
        {
            var users = _authService.GetAllUsers();
            return View(users);
        }

        public IActionResult Create()
        {
            return View(new UserDtoForCreation()
            {
                Roles = new HashSet<string>(_authService.Roles.Select(n => n.Name).ToList())
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] UserDtoForCreation userDto)
        {
            // Yeni oluşturulan kullanıcıya varsayılan olarak "Editor" rolünü ekleyelim
            userDto.Roles.Add("Editor");

            var result = await _authService.CreateUser(userDto);
            return result.Succeeded
                ? RedirectToAction("Index")
                : View(userDto);
        }

        public async Task<IActionResult> Update([FromRoute(Name = "id")] string id)
        {
            var result = await _authService.GetUserForUpdate(id);
            if (result == null)
            {
                return NotFound("Kullanıcı bulunamadı.");
            }
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] UserDtoForUpdate userDto)
        {
            if (ModelState.IsValid)
            {
                var updateResult =  _authService.Update(userDto);
                if (!updateResult.IsCompleted)
                {
                    ModelState.AddModelError("", "Kullanıcı güncellenemedi.");
                    return View(userDto);
                }

                return RedirectToAction("Index");
            }
            return View(userDto);
        }


        public async Task<IActionResult> ResetPassword([FromRoute(Name = "id")] string id)
        {
            return View(new ResetPasswordDto()
            {
                UserName = id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword([FromForm] ResetPasswordDto model)
        {
            var result = await _authService.ResetPassword(model);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Şifreniz : En az bir özel karakter (örneğin: !, @, #, $, %, vb.) içermelidir.");
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOneUser([FromForm] UserDto model)
        {
            var result = await _authService.DeleteOneUser(model.UserName);

            return result.Succeeded
                ? RedirectToAction("Index")
                : View(model);
        }
    }
}

MachineSimulation.App/Controllers/MachineController.cs
using AutoMapper;
using EasyModbus;
using MachineSimulation.Business.Abstract;
using MachineSimulation.Business.Concrete;
using MachineSimulation.DataAccess.Abstract.MachineRepositories;
using MachineSimulation.Entities.Concrete;
using MachineSimulation.Entities.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MachineSimulation.App.Controllers
{

    public class MachineController : Controller
	{
		private readonly IMachineService _machineService;
        private readonly IMachineLogService _machineLogService;
        private readonly IOperationLogService _operationLogService;
        public IMapper Mapper { get; }
        private readonly IModbusConnectionService _modbusConnectionService;


        private ModbusClient _modbusClient;

        public MachineController(IMapper mapper, IMachineService machineService, IMachineLogService machineLogService, IModbusConnectionService modbusConnectionService, IOperationLogService operationLogService)
        {
            Mapper = mapper;
            _machineService = machineService;
            _machineLogService = machineLogService;
            _modbusConnectionService = modbusConnectionService;
            _operationLogService = operationLogService;
        }
        public async Task<IActionResult> Index()
        {
			var model = await _machineService.GetAllMachinesAsync();
			return View(model);
		}

        [Authorize(Roles = "Admin,Editor")]
        [HttpGet]
        public async Task<IActionResult> ModbusConnect(int machineId)
        {
            var success = false; // Bağlantı başarılı mı?
            try
            {
                
                    string ipAddress = "192.168.0.231";
                    int port = 502;
                    int slaveId = 1;
                var modbusClient = _modbusConnectionService.GetOrCreateModbusClient(machineId, ipAddress, port, (byte)slaveId);
                modbusClient.Connect();
                success = modbusClient.Connected;
            }
            catch (Exception ex)
            {
                success = false;
                await _machineLogService.LogActionAsync(new MachineLog
                {
                    MachineId = machineId,
                    Action = "Bağlantı Hatası - " + ex.Message,
                    Timestamp = DateTime.UtcNow
                });
            }
            if (success)
            {
                await _machineLogService.LogActionAsync(new MachineLog
                {
                    MachineId = machineId,
                    Action = "Bağlandı",
                    Timestamp = DateTime.UtcNow
                });
            }

            return Ok(success);
        }

        [Authorize(Roles = "Admin,Editor")]
        [HttpGet]
        public async Task<IActionResult> ModbusDisconnect(int machineId)
        {
            var success = false;

            try
            {
                _modbusConnectionService.DisconnectModbusClient(machineId);
                success = true;
            }
            catch (Exception ex)
            {
                await _machineLogService.LogActionAsync(new MachineLog
                {
                    MachineId = machineId,
                    Action = "Bağlantı Kesme Hatası - " + ex.Message,
                    Timestamp = DateTime.UtcNow
                });
                return Ok(false);
            }

            if (success)
            {
                await _machineLogService.LogActionAsync(new MachineLog
                {
                    MachineId = machineId,
                    Action = "Kopartıldı",
                    Timestamp = DateTime.UtcNow
                });
            }

            return Ok(success);
        }

        [Authorize(Roles = "Admin,Editor")]
        [HttpGet]
        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model =  _machineService.GetMachineDetails(id);
            model.OperationLogs = _operationLogService.GetOperationLogsWithNames(id);
            model.Stopages=_machineService.GetStoppages(id);
            return View(model);
        }

        [HttpGet("Machine/Get/Machine/GetMachineParameters/{id}")]
        public IActionResult GetMachineParameters([FromRoute(Name = "id")] int id)
        {
            var model = _machineService.GetParameters(id);

            if (model == null)
            {
                return NotFound();
            }

            return Ok(model);
        }

      

        [HttpGet("machine/getLogs/{machineId}")]
        public IActionResult GetLogs(int machineId)
        {
            var logs = _operationLogService.GetLogsForMachine(machineId);
            return Json(logs);
        }


        [HttpPost]
        [Route("/machine/logoperation")]
        public async Task<IActionResult> LogOperation([FromBody] OperationLog operationLog)
        {
            if (operationLog == null)
            {
                return BadRequest("Operation log cannot be null.");
            }

            await _operationLogService.AddOperationLogAsync(operationLog);
            return Ok(new { message = "Log recorded successfully." });
        }


    }
}

MachineSimulation.App/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CoralReef Tablet Makine Entegrasyonu</title>
    <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MachineSimulation.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_Navbar" /> 

        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        @RenderSection("Footer", false)
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MachineSimulation.App/Areas/Admin/Views/Shared/_Navbar.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar Example</title>
    <link rel="stylesheet" href="~/css/admin-navbar.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
       
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark ">
        <a class="navbar-brand" asp-controller="Dashboard" asp-action="Index">
            <img src="~/images/iletisim-yazilim.png" alt="Logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
               
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Machine" asp-action="Index">Makineler</a>
                </li>

                 <li class="nav-item">
                    <a class="nav-link" asp-controller="Operation" asp-action="Index">Operasyonlar</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Parameter" asp-action="Index">Parametreler</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Stoppage" asp-action="Index">Duruşlar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="ModbusAddress" asp-action="Index">Kriter Adresi</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Yönetim
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" asp-controller="Role" asp-action="Index">Roller</a></li>
                        <li><a class="dropdown-item" asp-controller="User" asp-action="Index">Kullanıcılar</a></li>
                        <li><a class="dropdown-item" asp-controller="User" asp-action="Create">Kullanıcı Oluştur</a></li>
                    </ul>
                </li>

            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Machine" asp-action="Index"><i class="bi bi-house-door-fill"></i> Ana Sayfa</a>
                </li>
            </ul>
        </div>
    </nav>

    @*     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> *@
</body>
</html>